[2025-02-01T22:05:06.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T22:05:06.584+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.spark_consumer scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T22:05:06.591+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.spark_consumer scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T22:05:06.593+0000] {taskinstance.py:2866} INFO - Starting attempt 7 of 12
[2025-02-01T22:05:06.602+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): spark_consumer> on 2025-01-31 00:00:00+00:00
[2025-02-01T22:05:06.607+0000] {standard_task_runner.py:72} INFO - Started process 3190 to run task
[2025-02-01T22:05:06.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'spark_consumer', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp3d9r88zx']
[2025-02-01T22:05:06.611+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask spark_consumer
[2025-02-01T22:05:06.647+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.spark_consumer scheduled__2025-01-31T00:00:00+00:00 [running]> on host 2f541c1544a4
[2025-02-01T22:05:06.705+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-02-01T22:05:06.706+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T22:05:17.916+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-01T22:05:18.670+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:19.419+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:20.168+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:20.917+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:21.664+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:22.437+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:23.192+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:23.965+0000] {sql.py:681} INFO - Loaded 1000 rows into crypto_data so far
[2025-02-01T22:05:24.541+0000] {sql.py:681} INFO - Loaded 760 rows into crypto_data so far
[2025-02-01T22:05:24.542+0000] {sql.py:694} INFO - Done loading. Loaded a total of 8760 rows into crypto_data
[2025-02-01T22:05:24.547+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T22:05:24.554+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T22:05:24.555+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=spark_consumer, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250201T220506, end_date=20250201T220524
[2025-02-01T22:05:24.600+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T22:05:24.613+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T22:05:24.615+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-01T22:27:54.931+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T22:27:54.945+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.spark_consumer scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T22:27:54.952+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.spark_consumer scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T22:27:54.953+0000] {taskinstance.py:2866} INFO - Starting attempt 7 of 12
[2025-02-01T22:27:54.962+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): spark_consumer> on 2025-01-31 00:00:00+00:00
[2025-02-01T22:27:54.967+0000] {standard_task_runner.py:72} INFO - Started process 2114 to run task
[2025-02-01T22:27:54.969+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'spark_consumer', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpanu7fzb_']
[2025-02-01T22:27:54.971+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask spark_consumer
[2025-02-01T22:27:55.006+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.spark_consumer scheduled__2025-01-31T00:00:00+00:00 [running]> on host aa1cd894ce8b
[2025-02-01T22:27:55.063+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-02-01T22:27:55.064+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T22:28:00.664+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2025-02-01T22:28:00.666+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 39709)
[2025-02-01T22:28:03.003+0000] {clientserver.py:561} INFO - Python Server ready to receive messages
[2025-02-01T22:28:03.004+0000] {clientserver.py:575} INFO - Received command c on object id p0
[2025-02-01T22:28:05.028+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-01T22:28:05.040+0000] {clientserver.py:621} ERROR - There was an exception while executing the Python Proxy on the Python Side.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 120, in call
    raise e
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
  File "/opt/airflow/dags/main_pipeline.py", line 169, in write_batch
    hook.insert_rows(table='crypto_data', rows=[data], target_fields=columns)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 679, in insert_rows
    cur.executemany(sql, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "price_change"
LINE 1: ...first_id, last_id, count, trend) VALUES ('symbol','price_cha...
                                                             ^

[2025-02-01T22:28:05.164+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 121, in spark_consumer
    write_to_postgres(df_parsed)
  File "/opt/airflow/dags/main_pipeline.py", line 175, in write_to_postgres
    .awaitTermination()
     ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = fcf01807-1711-468e-94d2-fb80ed117c95, runId = 5a43eb88-266c-45bc-a6aa-63c4d5946fa9] terminated with exception: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 120, in call
    raise e
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
  File "/opt/airflow/dags/main_pipeline.py", line 169, in write_batch
    hook.insert_rows(table='crypto_data', rows=[data], target_fields=columns)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 679, in insert_rows
    cur.executemany(sql, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "price_change"
LINE 1: ...first_id, last_id, count, trend) VALUES ('symbol','price_cha...
                                                             ^


[2025-02-01T22:28:05.179+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=save_to_minio, task_id=spark_consumer, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250201T222754, end_date=20250201T222805
[2025-02-01T22:28:05.194+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T22:28:05.195+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task spark_consumer ([STREAM_FAILED] Query [id = fcf01807-1711-468e-94d2-fb80ed117c95, runId = 5a43eb88-266c-45bc-a6aa-63c4d5946fa9] terminated with exception: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 120, in call
    raise e
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
  File "/opt/airflow/dags/main_pipeline.py", line 169, in write_batch
    hook.insert_rows(table='crypto_data', rows=[data], target_fields=columns)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 679, in insert_rows
    cur.executemany(sql, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "price_change"
LINE 1: ...first_id, last_id, count, trend) VALUES ('symbol','price_cha...
                                                             ^

; 2114)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 121, in spark_consumer
    write_to_postgres(df_parsed)
  File "/opt/airflow/dags/main_pipeline.py", line 175, in write_to_postgres
    .awaitTermination()
     ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = fcf01807-1711-468e-94d2-fb80ed117c95, runId = 5a43eb88-266c-45bc-a6aa-63c4d5946fa9] terminated with exception: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/clientserver.py", line 617, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 120, in call
    raise e
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/utils.py", line 117, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
  File "/opt/airflow/dags/main_pipeline.py", line 169, in write_batch
    hook.insert_rows(table='crypto_data', rows=[data], target_fields=columns)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 679, in insert_rows
    cur.executemany(sql, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "price_change"
LINE 1: ...first_id, last_id, count, trend) VALUES ('symbol','price_cha...
                                                             ^


[2025-02-01T22:28:05.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-01T22:28:05.249+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T22:28:05.252+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
