[2025-01-29T15:02:55.222+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T15:02:55.238+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-01-29T15:02:55.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-01-29T15:02:55.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-29T15:02:55.263+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-01-29T15:02:55.268+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-01-29T15:02:55.272+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp3nlqfkjb']
[2025-01-29T15:02:55.275+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-01-29T15:02:55.317+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 21ecc35bc506
[2025-01-29T15:02:55.384+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-01-29T15:02:55.386+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T15:02:58.343+0000] {base_aws.py:603} WARNING - Unable to find AWS Connection ID 'minio_conn', switching to empty.
[2025-01-29T15:02:58.344+0000] {base_aws.py:177} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-01-29T15:02:58.874+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 25, in save_to_minio
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 152, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 125, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1197, in load_string
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1280, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 135, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 158, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/upload.py", line 762, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 197, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-01-29T15:02:58.887+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250129T150255, end_date=20250129T150258
[2025-01-29T15:02:58.899+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T15:02:58.900+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task save_to_minio (Unable to locate credentials; 196)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 25, in save_to_minio
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 152, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 125, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1197, in load_string
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1280, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 135, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 158, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/upload.py", line 762, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 197, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-01-29T15:02:58.947+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-29T15:02:58.964+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T15:02:58.966+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-29T16:00:45.161+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T16:00:45.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-01-29T16:00:45.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-01-29T16:00:45.181+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-29T16:00:45.190+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-01-29T16:00:45.194+0000] {standard_task_runner.py:72} INFO - Started process 339 to run task
[2025-01-29T16:00:45.197+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp9alo0l45']
[2025-01-29T16:00:45.199+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-01-29T16:00:45.233+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 5814ec6b4fbb
[2025-01-29T16:00:45.297+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-01-29T16:00:45.298+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T16:00:47.408+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-01-29T16:00:47.409+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-01-29T16:00:47.804+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 25, in save_to_minio
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 152, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 125, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1197, in load_string
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1280, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 135, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 158, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/upload.py", line 762, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
[2025-01-29T16:00:47.814+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250129T160045, end_date=20250129T160047
[2025-01-29T16:00:47.826+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T16:00:47.827+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task save_to_minio (An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist; 339)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 25, in save_to_minio
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 152, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 125, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1197, in load_string
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1280, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 135, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 158, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/upload.py", line 762, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
[2025-01-29T16:00:47.858+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-29T16:00:47.873+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T16:00:47.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:22:40.299+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:22:40.319+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:22:40.327+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:22:40.329+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:22:40.342+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T13:22:40.348+0000] {standard_task_runner.py:72} INFO - Started process 262 to run task
[2025-02-02T13:22:40.351+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpg5kvktfq']
[2025-02-02T13:22:40.354+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask save_to_minio
[2025-02-02T13:22:40.412+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host e6ed12b0dfa5
[2025-02-02T13:22:40.503+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T13:22:40.505+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:22:42.753+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:22:42.754+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:22:44.374+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:22:44.387+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:22:44.388+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T132240, end_date=20250202T132244
[2025-02-02T13:22:44.464+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:22:44.498+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:22:44.502+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:37:02.329+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:37:02.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:37:02.346+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:37:02.347+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:37:02.356+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T13:37:02.360+0000] {standard_task_runner.py:72} INFO - Started process 455 to run task
[2025-02-02T13:37:02.362+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpels84ivc']
[2025-02-02T13:37:02.364+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T13:37:02.399+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 64f2a5764477
[2025-02-02T13:37:02.464+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T13:37:02.465+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:37:04.570+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:37:04.571+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:37:04.937+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:37:04.945+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:37:04.946+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T133702, end_date=20250202T133704
[2025-02-02T13:37:04.983+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:37:05.003+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:37:05.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:50:27.444+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:50:27.456+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:50:27.461+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:50:27.462+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:50:27.471+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T13:50:27.475+0000] {standard_task_runner.py:72} INFO - Started process 1651 to run task
[2025-02-02T13:50:27.477+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpx3zitmve']
[2025-02-02T13:50:27.479+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask save_to_minio
[2025-02-02T13:50:27.511+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 774492c58bf0
[2025-02-02T13:50:27.565+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T13:50:27.567+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:50:30.834+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:50:30.835+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:50:31.197+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:50:31.205+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:50:31.206+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T135027, end_date=20250202T135031
[2025-02-02T13:50:31.263+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:50:31.282+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:50:31.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:58:37.130+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:58:37.142+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:58:37.147+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T13:58:37.148+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:58:37.157+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T13:58:37.161+0000] {standard_task_runner.py:72} INFO - Started process 454 to run task
[2025-02-02T13:58:37.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpr35x79l2']
[2025-02-02T13:58:37.165+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T13:58:37.196+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host f0b94dd433bd
[2025-02-02T13:58:37.254+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T13:58:37.255+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:58:41.152+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:58:41.153+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:58:41.490+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:58:41.497+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:58:41.498+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T135837, end_date=20250202T135841
[2025-02-02T13:58:41.550+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:58:41.570+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:58:41.572+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:17:39.215+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:17:39.228+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:17:39.236+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:17:39.237+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:17:39.247+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T14:17:39.253+0000] {standard_task_runner.py:72} INFO - Started process 1645 to run task
[2025-02-02T14:17:39.255+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp8kkvlpwf']
[2025-02-02T14:17:39.258+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask save_to_minio
[2025-02-02T14:17:39.296+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 5ab92388ff22
[2025-02-02T14:17:39.357+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T14:17:39.358+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:17:42.942+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:17:42.944+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:17:43.321+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:17:43.329+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:17:43.330+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T141739, end_date=20250202T141743
[2025-02-02T14:17:43.361+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:17:43.384+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:17:43.386+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:33:27.893+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:33:27.905+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:33:27.912+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:33:27.913+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:33:27.922+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T14:33:27.926+0000] {standard_task_runner.py:72} INFO - Started process 1221 to run task
[2025-02-02T14:33:27.928+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpbzp2eau0']
[2025-02-02T14:33:27.930+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask save_to_minio
[2025-02-02T14:33:27.964+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host a499fcfb67cb
[2025-02-02T14:33:28.026+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T14:33:28.027+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:33:31.868+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:33:31.869+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:33:32.211+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:33:32.218+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:33:32.219+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T143327, end_date=20250202T143332
[2025-02-02T14:33:32.275+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:33:32.294+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:33:32.296+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:36:19.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:36:19.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:36:19.990+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:36:19.992+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:36:20.001+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T14:36:20.006+0000] {standard_task_runner.py:72} INFO - Started process 588 to run task
[2025-02-02T14:36:20.008+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpbrnr2amc']
[2025-02-02T14:36:20.010+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T14:36:20.046+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host be62f1cf8682
[2025-02-02T14:36:20.109+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T14:36:20.111+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:36:23.726+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:36:23.727+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:36:24.063+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:36:24.071+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:36:24.071+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T143619, end_date=20250202T143624
[2025-02-02T14:36:24.115+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:36:24.137+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:36:24.139+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:46:41.879+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:46:41.890+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:46:41.895+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:46:41.895+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:46:41.903+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T14:46:41.907+0000] {standard_task_runner.py:72} INFO - Started process 462 to run task
[2025-02-02T14:46:41.910+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp3o6vqimz']
[2025-02-02T14:46:41.912+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T14:46:41.943+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 63894a7c3fe6
[2025-02-02T14:46:41.996+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T14:46:41.997+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:46:45.812+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:46:45.814+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:46:46.151+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:46:46.158+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:46:46.159+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T144641, end_date=20250202T144646
[2025-02-02T14:46:46.187+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:46:46.205+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:46:46.207+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:58:54.501+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:58:54.512+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:58:54.518+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T14:58:54.519+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:58:54.528+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T14:58:54.532+0000] {standard_task_runner.py:72} INFO - Started process 445 to run task
[2025-02-02T14:58:54.535+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpqodrwnpa']
[2025-02-02T14:58:54.537+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T14:58:54.569+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host a75ab04d6f73
[2025-02-02T14:58:54.621+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T14:58:54.622+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:58:57.908+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:58:57.909+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:58:58.293+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:58:58.300+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:58:58.301+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T145854, end_date=20250202T145858
[2025-02-02T14:58:58.360+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:58:58.380+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:58:58.382+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T15:48:04.478+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T15:48:04.489+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T15:48:04.495+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T15:48:04.495+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T15:48:04.506+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T15:48:04.511+0000] {standard_task_runner.py:72} INFO - Started process 2133 to run task
[2025-02-02T15:48:04.513+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpp79pw4am']
[2025-02-02T15:48:04.516+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask save_to_minio
[2025-02-02T15:48:04.550+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host d42d69d5511c
[2025-02-02T15:48:04.613+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T15:48:04.614+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T15:48:08.978+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T15:48:08.979+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T15:48:09.318+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T15:48:09.325+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T15:48:09.326+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T154804, end_date=20250202T154809
[2025-02-02T15:48:09.380+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T15:48:09.403+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T15:48:09.404+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T15:52:12.294+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T15:52:12.306+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T15:52:12.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T15:52:12.312+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T15:52:12.321+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T15:52:12.325+0000] {standard_task_runner.py:72} INFO - Started process 475 to run task
[2025-02-02T15:52:12.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpe8avqqiw']
[2025-02-02T15:52:12.329+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T15:52:12.361+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 7bf4a44673c6
[2025-02-02T15:52:12.423+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T15:52:12.424+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T15:52:16.270+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T15:52:16.271+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T15:52:16.612+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T15:52:16.619+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T15:52:16.620+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T155212, end_date=20250202T155216
[2025-02-02T15:52:16.674+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T15:52:16.694+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T15:52:16.696+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T16:12:47.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T16:12:47.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T16:12:47.845+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T16:12:47.846+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T16:12:47.856+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T16:12:47.861+0000] {standard_task_runner.py:72} INFO - Started process 1520 to run task
[2025-02-02T16:12:47.863+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp0vm6vv5o']
[2025-02-02T16:12:47.866+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask save_to_minio
[2025-02-02T16:12:47.906+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 4061bda98b6f
[2025-02-02T16:12:47.985+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T16:12:47.986+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T16:12:50.121+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T16:12:50.122+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T16:12:50.482+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T16:12:50.490+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T16:12:50.490+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T161247, end_date=20250202T161250
[2025-02-02T16:12:50.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T16:12:50.543+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T16:12:50.545+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T18:40:22.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T18:40:22.118+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T18:40:22.124+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T18:40:22.126+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T18:40:22.135+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T18:40:22.140+0000] {standard_task_runner.py:72} INFO - Started process 1832 to run task
[2025-02-02T18:40:22.142+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp6qjt6mhw']
[2025-02-02T18:40:22.144+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask save_to_minio
[2025-02-02T18:40:22.181+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 15904aeddad7
[2025-02-02T18:40:22.242+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T18:40:22.243+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T18:40:24.389+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T18:40:24.391+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T18:40:24.773+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T18:40:24.780+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T18:40:24.781+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T184022, end_date=20250202T184024
[2025-02-02T18:40:24.803+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T18:40:24.825+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T18:40:24.827+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T19:20:38.906+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:20:38.918+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T19:20:38.924+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T19:20:38.925+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T19:20:38.934+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T19:20:38.939+0000] {standard_task_runner.py:72} INFO - Started process 554 to run task
[2025-02-02T19:20:38.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp8rvoq8qs']
[2025-02-02T19:20:38.943+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T19:20:38.977+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host dfbcbb9a3a68
[2025-02-02T19:20:39.036+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T19:20:39.037+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:20:42.346+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T19:20:42.348+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T19:20:42.722+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T19:20:42.730+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:20:42.731+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T192038, end_date=20250202T192042
[2025-02-02T19:20:42.765+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T19:20:42.784+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T19:20:42.786+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T19:53:50.192+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:53:50.207+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T19:53:50.216+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T19:53:50.217+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T19:53:50.227+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T19:53:50.231+0000] {standard_task_runner.py:72} INFO - Started process 555 to run task
[2025-02-02T19:53:50.234+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp15idplrm']
[2025-02-02T19:53:50.236+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T19:53:50.275+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host cc19208c71dd
[2025-02-02T19:53:50.341+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T19:53:50.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:53:52.987+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T19:53:52.988+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T19:53:53.338+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T19:53:53.347+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:53:53.348+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T195350, end_date=20250202T195353
[2025-02-02T19:53:53.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T19:53:53.398+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T19:53:53.400+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T19:56:53.041+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:56:53.054+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T19:56:53.061+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T19:56:53.063+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T19:56:53.073+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T19:56:53.078+0000] {standard_task_runner.py:72} INFO - Started process 532 to run task
[2025-02-02T19:56:53.080+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmptrnf3ry2']
[2025-02-02T19:56:53.083+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T19:56:53.119+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host ad5c63f64f40
[2025-02-02T19:56:53.177+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T19:56:53.178+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:56:55.904+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T19:56:55.905+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T19:56:56.246+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T19:56:56.254+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:56:56.255+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T195653, end_date=20250202T195656
[2025-02-02T19:56:56.304+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T19:56:56.322+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T19:56:56.324+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:09:11.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:09:11.557+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:09:11.564+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:09:11.566+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:09:11.576+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T20:09:11.581+0000] {standard_task_runner.py:72} INFO - Started process 554 to run task
[2025-02-02T20:09:11.583+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpnctbpwra']
[2025-02-02T20:09:11.586+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T20:09:11.623+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 6df1dc328a9b
[2025-02-02T20:09:11.696+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T20:09:11.697+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:09:14.948+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:09:14.950+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:09:15.328+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:09:15.335+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:09:15.337+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T200911, end_date=20250202T200915
[2025-02-02T20:09:15.371+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:09:15.389+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:09:15.391+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:17:15.735+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:17:15.751+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:17:15.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:17:15.764+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:17:15.779+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T20:17:15.786+0000] {standard_task_runner.py:72} INFO - Started process 563 to run task
[2025-02-02T20:17:15.788+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp169l4ozs']
[2025-02-02T20:17:15.791+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T20:17:15.836+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host b0b992709001
[2025-02-02T20:17:15.920+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T20:17:15.922+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:17:19.439+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:17:19.440+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:17:19.781+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:17:19.788+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:17:19.789+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T201715, end_date=20250202T201719
[2025-02-02T20:17:19.814+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:17:19.832+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:17:19.835+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:40:42.970+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:40:42.981+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:40:42.987+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:40:42.988+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:40:42.998+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T20:40:43.002+0000] {standard_task_runner.py:72} INFO - Started process 293 to run task
[2025-02-02T20:40:43.004+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpkv6ypjd7']
[2025-02-02T20:40:43.006+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T20:40:43.037+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 7ed9c07bce51
[2025-02-02T20:40:43.098+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T20:40:43.099+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:40:47.235+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:40:47.236+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:40:47.607+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:40:47.614+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:40:47.615+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T204042, end_date=20250202T204047
[2025-02-02T20:40:47.670+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:40:47.688+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:40:47.690+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:45:19.292+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:45:19.314+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:45:19.333+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [queued]>
[2025-02-02T20:45:19.335+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:45:19.356+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-28 00:00:00+00:00
[2025-02-02T20:45:19.363+0000] {standard_task_runner.py:72} INFO - Started process 587 to run task
[2025-02-02T20:45:19.366+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpituuojl4']
[2025-02-02T20:45:19.371+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask save_to_minio
[2025-02-02T20:45:19.443+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-28T00:00:00+00:00 [running]> on host 12998e952c77
[2025-02-02T20:45:19.548+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-28T00:00:00+00:00'
[2025-02-02T20:45:19.550+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:45:22.226+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:45:22.227+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:45:22.584+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:45:22.591+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:45:22.592+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-28T00:00:00+00:00, execution_date=20250128T000000, start_date=20250202T204519, end_date=20250202T204522
[2025-02-02T20:45:22.633+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:45:22.649+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:45:22.653+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
