[2025-02-04T19:47:51.140+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T19:47:51.151+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_consumer_dag.spark_consumer scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-04T19:47:51.157+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_consumer_dag.spark_consumer scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-04T19:47:51.158+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2025-02-04T19:47:51.166+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): spark_consumer> on 2025-01-27 00:00:00+00:00
[2025-02-04T19:47:51.170+0000] {standard_task_runner.py:72} INFO - Started process 335 to run task
[2025-02-04T19:47:51.172+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_consumer_dag', 'spark_consumer', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/consumer.py', '--cfg-path', '/tmp/tmpeeshw0c4']
[2025-02-04T19:47:51.174+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask spark_consumer
[2025-02-04T19:47:51.211+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_consumer_dag.spark_consumer scheduled__2025-01-27T00:00:00+00:00 [running]> on host 7ffbfde90b16
[2025-02-04T19:47:51.280+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='spark_consumer_dag' AIRFLOW_CTX_TASK_ID='spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-04T19:47:51.282+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T19:47:51.301+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-02-04T19:47:51.303+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.jars.packages=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4 --conf spark.jars=/opt/postgresql-42.2.23.jar --num-executors 1 --executor-cores 1 --executor-memory 1g --driver-memory 512m --name arrow-spark --queue root.default /opt/***/dags/spark_consumer.py --kafka-bootstrap-servers kafka:9093 --topic crypto_topic --jdbc-url jdbc:postgresql://postgres:5432/test --user *** --password ******
[2025-02-04T19:47:51.365+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-04T19:47:52.686+0000] {spark_submit.py:641} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-02-04T19:47:52.688+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-02-04T19:47:52.688+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-02-04T19:47:52.689+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-02-04T19:47:52.690+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-02-04T19:47:52.691+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-02-04T19:47:52.691+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-02-04T19:47:52.692+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-02-04T19:47:52.693+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-02-04T19:47:52.693+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-02-04T19:47:52.694+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-02-04T19:47:52.704+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.jars.packages=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4 --conf spark.jars=/opt/postgresql-42.2.23.jar --num-executors 1 --executor-cores 1 --executor-memory 1g --driver-memory 512m --name arrow-spark --queue root.default /opt/***/dags/spark_consumer.py --kafka-bootstrap-servers kafka:9093 --topic crypto_topic --jdbc-url jdbc:postgresql://postgres:5432/test --user *** --password ******. Error code is: 1.
[2025-02-04T19:47:52.710+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_consumer_dag, task_id=spark_consumer, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250204T194751, end_date=20250204T194752
[2025-02-04T19:47:52.724+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T19:47:52.725+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task spark_consumer (Cannot execute: spark-submit --master yarn --conf spark.jars.packages=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4 --conf spark.jars=/opt/postgresql-42.2.23.jar --num-executors 1 --executor-cores 1 --executor-memory 1g --driver-memory 512m --name arrow-spark --queue root.default /opt/***/dags/spark_consumer.py --kafka-bootstrap-servers kafka:9093 --topic crypto_topic --jdbc-url jdbc:postgresql://postgres:5432/test --user *** --password ******. Error code is: 1.; 335)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.jars.packages=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.4 --conf spark.jars=/opt/postgresql-42.2.23.jar --num-executors 1 --executor-cores 1 --executor-memory 1g --driver-memory 512m --name arrow-spark --queue root.default /opt/***/dags/spark_consumer.py --kafka-bootstrap-servers kafka:9093 --topic crypto_topic --jdbc-url jdbc:postgresql://postgres:5432/test --user *** --password ******. Error code is: 1.
[2025-02-04T19:47:52.750+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-04T19:47:52.765+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T19:47:52.767+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
